=== se-panfilov/anarchy-engine/src/Engine/Schemas/ILevelConfig.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "scenes": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ISceneConfig"
      }
    },
    "actors": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/IActorConfig"
      }
    },
    "cameras": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ICameraConfig"
      }
    },
    "lights": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ILightConfig"
      }
    },
    "controls": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/IControlsConfig"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/LevelTag"
          },
          {
            "$ref": "#/definitions/CommonTags"
          },
          {
            "type": "string"
          }
        ]
      }
    }
  },
  "required": ["name", "scenes", "actors", "cameras", "lights", "controls", "tags"],
  "additionalProperties": false,
  "definitions": {
    "ISceneConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "background": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/SceneTag"
              },
              {
                "$ref": "#/definitions/CommonTags"
              },
              {
                "type": "string"
              }
            ]
          }
        }
      },
      "required": ["name", "tags"]
    },
    "SceneTag": {
      "type": "string",
      "const": "current"
    },
    "CommonTags": {
      "type": "string",
      "const": "from_config"
    },
    "IActorConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "$ref": "#/definitions/ActorType"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "materialParams": {
          "$ref": "#/definitions/IActorMaterialConfig"
        },
        "position": {
          "$ref": "#/definitions/IVector3dConfig"
        },
        "castShadow": {
          "type": "boolean"
        },
        "depth": {
          "type": "number"
        },
        "radius": {
          "type": "number"
        },
        "widthSegments": {
          "type": "number"
        },
        "heightSegments": {
          "type": "number"
        },
        "depthSegments": {
          "type": "number"
        },
        "rotation": {
          "$ref": "#/definitions/IVector3"
        },
        "tags": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/ActorTag"
              },
              {
                "$ref": "#/definitions/CommonTags"
              },
              {
                "type": "string"
              }
            ]
          }
        }
      },
      "required": ["castShadow", "height", "materialParams", "position", "tags", "type", "width"]
    },
    "ActorType": {
      "type": "string",
      "enum": ["sphere", "plane", "cube"]
    },
    "IActorMaterialConfig": {
      "type": "object",
      "properties": {
        "color": {
          "type": "string"
        }
      },
      "required": ["color"],
      "additionalProperties": false
    },
    "IVector3dConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        },
        "z": {
          "type": "number"
        }
      },
      "required": ["x", "y", "z"]
    },
    "IVector3": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number",
          "default": 0
        },
        "y": {
          "type": "number",
          "default": 0
        },
        "z": {
          "type": "number",
          "default": 0
        },
        "isVector3": {
          "type": "boolean",
          "const": true
        }
      },
      "required": ["x", "y", "z", "isVector3"],
      "additionalProperties": false
    },
    "ActorTag": {
      "type": "string",
      "const": "intersectable"
    },
    "ICameraConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lookAt": {
          "$ref": "#/definitions/IVector3dConfig"
        },
        "position": {
          "$ref": "#/definitions/IVector3dConfig"
        },
        "fov": {
          "type": "number"
        },
        "near": {
          "type": "number"
        },
        "far": {
          "type": "number"
        },
        "tags": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/CameraTag"
              },
              {
                "$ref": "#/definitions/CommonTags"
              },
              {
                "type": "string"
              }
            ]
          }
        }
      },
      "required": ["lookAt", "position", "tags"]
    },
    "CameraTag": {
      "type": "string",
      "const": "initial"
    },
    "ILightConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "$ref": "#/definitions/ILightType"
        },
        "color": {
          "type": "string"
        },
        "intensity": {
          "type": "number"
        },
        "castShadow": {
          "type": "boolean"
        },
        "shadow": {
          "$ref": "#/definitions/LightShadowConfig"
        },
        "position": {
          "$ref": "#/definitions/IVector3dConfig"
        },
        "tags": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/LightTag"
              },
              {
                "$ref": "#/definitions/CommonTags"
              },
              {
                "type": "string"
              }
            ]
          }
        }
      },
      "required": ["castShadow", "color", "intensity", "position", "tags", "type"]
    },
    "ILightType": {
      "type": "string",
      "enum": ["ambient", "directional"]
    },
    "LightShadowConfig": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "mapSize": {
          "$ref": "#/definitions/IVector2dConfig"
        },
        "camera": {
          "type": "object",
          "properties": {
            "far": {
              "type": "number"
            }
          },
          "required": ["far"],
          "additionalProperties": false
        },
        "normalBias": {
          "type": "number"
        }
      },
      "required": ["camera", "mapSize", "normalBias"]
    },
    "IVector2dConfig": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": ["x", "y"],
      "additionalProperties": false
    },
    "LightTag": {
      "type": "string",
      "const": "ambient"
    },
    "IControlsConfig": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/IControlsType"
        },
        "cameraTag": {
          "$ref": "#/definitions/CameraTag"
        },
        "enableDamping": {
          "type": "boolean"
        },
        "tags": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#/definitions/ControlsTag"
              },
              {
                "$ref": "#/definitions/CommonTags"
              },
              {
                "type": "string"
              }
            ]
          }
        }
      },
      "required": ["type", "cameraTag", "tags"],
      "additionalProperties": false
    },
    "IControlsType": {
      "type": "string",
      "const": "OrbitControls"
    },
    "ControlsTag": {
      "type": "string",
      "const": "initial"
    },
    "LevelTag": {
      "type": "string",
      "const": "build-in"
    }
  }
}

=== se-panfilov/anarchy-engine/src/App/Levels/ShowcaseLevel2/showcase-level-1.config.json
{
  "name": "Showcase level 01",
  "scenes": [
    {
      "name": "Showcase Scene 01",
      "tags": ["current"]
    }
  ],
  "actors": [],
  "cameras": [
    {
      "fov": 45,
      "near": 1,
      "far": 10000,
      "position": { "x": 3, "y": 20, "z": 35 },
      "lookAt": { "x": 0, "y": 0, "z": 0 },
      "tags": ["initial"]
    }
  ],
  "lights": [
    {
      "type": "ambient",
      "color": "#ffffff",
      "intensity": 0.5,
      "castShadow": false,
      "position": { "x": 0.25, "y": 2, "z": 2.25 },
      "tags": []
    },
    {
      "type": "directional",
      "color": "#ffffff",
      "intensity": 1,
      "castShadow": true,
      "shadow": {
        "mapSize": { "x": 1024, "y": 1024 },
        "camera": { "far": 15 },
        "normalBias": 0.05
      },
      "position": { "x": 0.25, "y": 2, "z": 2.25 },
      "tags": []
    }
  ],
  "controls": [
    {
      "type": "OrbitControls",
      "cameraTag": "initial",
      "enableDamping": true,
      "tags": []
    }
  ],
  "tags": ["build-in"]
}
